package com.ComponentesProyecto.ProyectoAPI.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

@DynamoDBTable(tableName = "marcas")
@Data
public class Marca {

    @DynamoDBHashKey(attributeName = "marca_id")
    @DynamoDBAutoGeneratedKey
    private String marca_id;

    @DynamoDBAttribute(attributeName = "nombre_marca")
    private String nombre_marca;

    @DynamoDBAttribute(attributeName = "num_expediente")
    private String num_expediente;

    @DynamoDBAttribute(attributeName = "fecha_presentacion")
    private String fecha_presentacion;

    @DynamoDBAttribute(attributeName = "num_registro")
    private int num_registro;

    @DynamoDBAttribute(attributeName = "fecha_registro")
    private String fecha_registro;

    @DynamoDBAttribute(attributeName = "fecha_publicacion")
    private String fecha_publicacion;

    @DynamoDBAttribute(attributeName = "nombre_solicitante")
    private String nombre_solicitante;


    @DynamoDBAttribute(attributeName = "tipo_solicitud")
    private String tipo_solicitud;

    @DynamoDBAttribute(attributeName = "subtipo_solicitud")
    private String subtipo_solicitud;

    @DynamoDBAttribute(attributeName = "estado")
    private String estado;





    //Mas columnas de la tabla....
}
